name: Deploy Project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.16.0]  # Explicitly set Node.js version to 16

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run your script
      env:
        DLAI_TOGETHER_API_BASE: ${{ secrets.DLAI_TOGETHER_API_BASE }}
        TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
      run: |
        python app.py
